In [5]:
import torch 

x_list = [[1,2,3],[4,5,6]]
x=torch.Tensor(x_list)

In [6]:
print(x.device)

cpu


In [8]:
print(torch.rand(2,3))

tensor([[0.3515, 0.5056, 0.2987],
        [0.7795, 0.2327, 0.3886]])


In [11]:
print(torch.randint(low=0, high=8, size=(2,3)))

tensor([[2, 3, 0],
        [1, 6, 3]])


In [13]:
x_zeros = torch.zeros_like(x.cpu())
print(x_zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [15]:
torch.manual_seed(1)
x = torch.randint(0, 10, size=(2,3,4))
print(x)

tensor([[[5, 9, 4, 8],
         [3, 3, 1, 1],
         [9, 2, 8, 9]],

        [[6, 3, 3, 0],
         [2, 1, 2, 6],
         [0, 3, 6, 4]]])


In [16]:
print(x.view(2,2,6))

tensor([[[5, 9, 4, 8, 3, 3],
         [1, 1, 9, 2, 8, 9]],

        [[6, 3, 3, 0, 2, 1],
         [2, 6, 0, 3, 6, 4]]])


In [17]:
print(x.view(-1,1,12))

tensor([[[5, 9, 4, 8, 3, 3, 1, 1, 9, 2, 8, 9]],

        [[6, 3, 3, 0, 2, 1, 2, 6, 0, 3, 6, 4]]])


In [19]:
x_transposed = x.transpose(0,1) #첫번째와 두번째 차원이 바뀜
print(x_transposed)

tensor([[[5, 9, 4, 8],
         [6, 3, 3, 0]],

        [[3, 3, 1, 1],
         [2, 1, 2, 6]],

        [[9, 2, 8, 9],
         [0, 3, 6, 4]]])


In [22]:
A = torch.LongTensor([[1,2,3],[4,5,6]])
print(A)
A.t()

tensor([[1, 2, 3],
        [4, 5, 6]])


tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [32]:
A=torch.rand(2,3)
print(A)

B=torch.rand(2,3)
print(B)

AB_concat = torch.cat([A,B], dim=1)
print(AB_concat)

tensor([[0.6601, 0.8238, 0.2413],
        [0.6084, 0.3180, 0.3877]])
tensor([[0.1015, 0.2721, 0.3469],
        [0.7138, 0.5913, 0.6235]])
tensor([[0.6601, 0.8238, 0.2413, 0.1015, 0.2721, 0.3469],
        [0.6084, 0.3180, 0.3877, 0.7138, 0.5913, 0.6235]])


In [35]:
AB_stack = torch.stack([A,B],dim=0)
print(AB_stack)
print(AB_stack.size())

tensor([[[0.6601, 0.8238, 0.2413],
         [0.6084, 0.3180, 0.3877]],

        [[0.1015, 0.2721, 0.3469],
         [0.7138, 0.5913, 0.6235]]])
torch.Size([2, 2, 3])


In [38]:
x = torch.LongTensor([1,2,3])
y = torch.LongTensor([3,4,5])

print(torch.add(x,y))
print(torch.sub(x,y))

tensor([4, 6, 8])
tensor([-2, -2, -2])


In [39]:
print(torch.mul(x,y))

tensor([ 3,  8, 15])


In [40]:
print(x*y)

tensor([ 3,  8, 15])


In [42]:
print(torch.dot(x,y))

tensor(26)


In [47]:
X = torch.Tensor([[1,4], [2,5], [3,6]])
Y = torch.Tensor([[7,9], [8,10]])

print(torch.mm(X,Y))

tensor([[39., 49.],
        [54., 68.],
        [69., 87.]])


In [48]:
z=torch.Tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
print(z)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [49]:
print(torch.max(z))

tensor(8.)


In [50]:
print(torch.argmax(z))

tensor(7)


In [52]:
print(torch.max(z,dim=1))

torch.return_types.max(
values=tensor([[3., 4.],
        [7., 8.]]),
indices=tensor([[1, 1],
        [1, 1]]))


In [1]:
def STEP(z):
    """step function"""
    return z>0

print(STEP(4))
print(STEP(0.1))
print(STEP(-1))

True
True
False


In [7]:
def AND(x,w,b):
    """AND function"""
    z=torch.dot(x,w)+b
    a=STEP(z)
    return a

def NAND(x,w,b):
    """NAND function"""
    z=torch.dot(x,w)+b
    a=STEP(z)
    return a

def OR(x,w,b):
    """OR function"""
    z=torch.dot(x,w)+b
    a=STEP(z)
    return a

w_and = torch.Tensor([0.5,0.5])
b_and = torch.Tensor([-0.7])
w_nand = torch.Tensor([-0.5, -0.5])
b_nand = torch.Tensor([0.7])
w_or = torch.Tensor([0.5, 0.5])
b_or = torch.Tensor([-0.2])

X = torch.Tensor([[0,0], [0,1], [1,0], [1,1]])
for x in X:
    print("input : {}".format(x.long().tolist()))
    print(" - AND:", AND(x, w=w_and, b=b_and).item())
    print(" - NAND:", NAND(x, w=w_nand, b=b_nand).item())
    print(" - OR:", OR(x, w=w_or, b=b_or).item())
    print("--"*15)

input : [0, 0]
 - AND: False
 - NAND: True
 - OR: False
------------------------------
input : [0, 1]
 - AND: False
 - NAND: True
 - OR: True
------------------------------
input : [1, 0]
 - AND: False
 - NAND: True
 - OR: True
------------------------------
input : [1, 1]
 - AND: True
 - NAND: False
 - OR: True
------------------------------


In [13]:
def solution(x, **kwargs):
    s1 = NAND(x, w=kwargs['w_nand'], b=kwargs['b_nand'])
    s2 = OR(x, w=kwargs['w_or'], b=kwargs['b_or'])
    y = AND(torch.Tensor([s1, s2]), w=kwargs['w_and'], b=kwargs['b_and'])
    return y

input_data=torch.FloatTensor([[0,0],[1,0],[0,1],[1,1]])
target_data = torch.ByteTensor([0,1,1,0])

kwargs = dict([('w_nand',w_nand), ('b_nand', b_nand), ('w_or', w_or), ('b_or', b_or), ('w_and', w_and), ('b_and', b_and)])

for x, y in zip(input_data, target_data):
    pred = solution (x, **kwargs)
    print("predict:{} | target: {}".format(pred.numpy(), y.numpy()))

predict:[False] | target: 0
predict:[ True] | target: 1
predict:[ True] | target: 1
predict:[False] | target: 0


In [15]:
#입력층에서 은닉층 코드

torch.manual_seed(70)
x = torch.Tensor([[0,1]])

W1 = torch.rand(2,2)
b1 = torch.rand(2,2)
z1 = torch.mm(x,W1.t())+b1
a1 = torch.sigmoid(z1)

In [20]:
def identify_func(x):
    """항등함수"""
    return x

W2=torch.rand((1,2))
b2=torch.rand((1,1))

z2=torch.mm(a1, W2.t())+b2
y=identify_func(z2)

print(y)

tensor([[1.3428],
        [1.4501]])


In [22]:
import torch.nn as nn
# 선형 결합, sigmoid 모듈 선언
linear_ih = nn.Linear(in_features=2, out_features=2) #input --> hidden layer
linear_ho = nn.Linear(in_features=2, out_features=1) #hidden --> output layer
activation_layer = nn.Sigmoid()

z1 = linear_ih(x)
a1 = activation_layer(z1)
z2 = linear_ho(a1)
y = identify_func(z2)
print(y.item())

-0.014880791306495667


In [24]:
class Network(nn.Module):
    """XOR Network"""
    def __init__(self, input_size, hidden_size, output_size):
        super().__init__()
        self.linear_ih = nn.Linear(in_features=input_size, out_features=hidden_size)
        self.linear_ho = nn.Linear(in_features=hidden_size, out_features=output_size)
        self.activation_layer = nn.Sigmoid()

    def identify_func(self, x):
        return x

    def forward(self, x):
        z1 = self.linear_ih(x)
        a1 = self.activation_layer(z1)
        z2 = self.linear_ho(a1)
        y = self.identify_func(z2)
        return y

net = Network(input_size =2, hidden_size =2, output_size=1)
y=net(x)
print(y.item())

-0.6631239056587219


In [44]:
#출력값을 확률로 표현하기 

class Network(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super().__init__()
        self.linear_ih = nn.Linear(in_features=input_size, out_features=hidden_size)
        self.linear_ho = nn.Linear(in_features=hidden_size, out_features=output_size)
        self.activation_layer = nn.Sigmoid()

    def forward(self, x):
        z1 = self.linear_ih(x)
        a1 = self.activation_layer(z1)
        z2 = self.linear_ho(a1)
        y = self.activation_layer(z2)
        return y

x = torch.Tensor([[0,0]])
net = Network(input_size =2, hidden_size = 2, output_size =1)
y = net(x)
print(y.item())

0.4284513592720032


In [28]:
P = torch.Tensor([0.4, 0.6]) #앞면이 40, 뒷면이 60 나올 확률의 동전
Q = torch.Tensor([0.0, 1.0]) #뒷면만 100퍼센트로 나오는 동전

def self_information(x):
    return -torch.log(x)

def entropy(x):
    e = 1e-30
    return torch.sum((x+e)*self_information(x+e))

print(entropy(P).numpy().round(4))
print(entropy(Q).numpy().round(4)) #항상 같은 면만 나오기 때문에 정보량이 없음

0.673
0.0


In [29]:
def KL_divergence(q, p):
    """q: predict prob, p: target prob"""
    e = 1e-30
    return torch.sum((p+e)*torch.log(p+e) - (p+e)*torch.log(q+e))

U = torch.Tensor([0.5, 0.5])
print (KL_divergence(P, U))
print(KL_divergence(Q,U))

tensor(0.0204)
tensor(33.8456)


In [31]:
loss_function = nn.KLDivLoss(reduction ="sum")
e =1e-30
print(loss_function(torch.log(P+e), U+e)) #확률분포 P와 U의 KL divergence
print(loss_function(torch.log(Q+e), U+e)) #확률분포 Q와 U의 KL divergence

tensor(0.0204)
tensor(33.8456)


In [33]:
#XOR 문제의 KL divergence 구하기

torch.manual_seed(70) #랜덤 시드 고정
x = torch.Tensor([[0,1]])
t = torch.Tensor([1])

net = Network(input_size=2, hidden_size =2, output_size =1)
y = net(x)

one_hot = torch.eye(2)
print(one_hot)
prob_t = one_hot.index_select(dim=0, index=t.long())

prob_y = torch.cat([1-y, y], dim=1) #예측값도 확률 분포로 만들어줌. y=1이 될 확률분포임
print(prob_t)
print(prob_y)

loss_function = nn.KLDivLoss(reduction="sum")
print(loss_function(torch.log(prob_y), prob_t))


tensor([[1., 0.],
        [0., 1.]])
tensor([[0., 1.]])
tensor([[0.5796, 0.4204]], grad_fn=<CatBackward0>)
tensor(0.8667, grad_fn=<SumBackward0>)


In [34]:
torch.manual_seed(70)

x = torch.Tensor([[0,1]])
t = torch.Tensor([1])

net = Network(input_size =2, hidden_size =2, output_size =1)
y = net(x)

loss_function = nn.BCELoss(reduction="sum")
print(loss_function(y.squeeze(1),t))

tensor(0.8667, grad_fn=<BinaryCrossEntropyBackward0>)


In [37]:
torch.manual_seed(70)
z = torch.rand(1,10)

y= torch.softmax(z, dim=1)
print(z)
print(y)

tensor([[0.4350, 0.3591, 0.3411, 0.2644, 0.6656, 0.1341, 0.7236, 0.6668, 0.1091,
         0.5745]])
tensor([[0.0986, 0.0914, 0.0897, 0.0831, 0.1241, 0.0729, 0.1315, 0.1243, 0.0711,
         0.1133]])


In [39]:
loss_function = nn.CrossEntropyLoss(reduction="sum")
print(loss_function(z, t.long()))

tensor(2.3930)


In [46]:
#XOR 문제에서 매개변수 몇개인지 구하기

import torch
import torch.nn as nn

torch.manual_seed(70)

class Network(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super().__init__()
        self.linear_ih = nn.Linear(in_features = input_size, out_features = hidden_size)
        self.linear_ho = nn.Linear(in_features = hidden_size, out_features = output_size)
        self.activation_layer = nn.Sigmoid()

    def forward(self, x):
        z1 = self.linear_ih(x)
        a1 = self.activation_layer(z1)
        z2 = self.linear_ho(a1)
        y = self.activation_layer(z2)
        return y

net = Network(input_size =2, hidden_size=2, output_size=1)
num_params = 0
for p in net.parameters():
    num_params += p.view(-1).size(0)
print(num_params)

9


In [48]:
def z_function(t):
    return t**2

def t_function(x, y):
    return x+y

def forward(x,y):
    t = t_function(x,y)
    z = z_function(t)
    return z


x = torch.Tensor([1])
y = torch.Tensor([2])
print(forward(x,y))

tensor([9.])


In [49]:
#역전파

def z_prime(t):
    """dz/dt"""
    return 2*t

def t_prime():
    """dt/dx = dt/dy"""
    return 1

def backward(t):
    """dz/dx"""
    dx = z_prime(t) * t_prime()
    return dx

x = torch.Tensor([1])
y = torch.Tensor([3])
t = t_function(x,y)
dx = backward(t)
print(dx)

tensor([8.])


In [51]:
#requires_grad_()
x = torch.Tensor([1]).requires_grad_()
y = torch.Tensor([3])
z = forward(x,y)

print("requires grad: x={}, y={}, z={}".format(x.requires_grad_(), y.requires_grad_(), z.requires_grad_()))
      
print("gradient function of z: {}".format(z.grad_fn))

z.backward()
print("dx = {}".format(x.grad))

requires grad: x=tensor([1.], requires_grad=True), y=tensor([3.], requires_grad=True), z=tensor([16.], grad_fn=<PowBackward0>)
gradient function of z: <PowBackward0 object at 0xf4730cb87940>
dx = tensor([8.])


In [52]:
#파이토치는 오차 역전파를 위한 도구를 torch.optim에 담음

#파이토치에서의 학습과정
#1. 입력 및 타겟 데이터 전처리, 모델, 손실함수 그리고 경사하강법을 수행하는 옵티마이저 정의
#2. 몇회 학습시킬지 결정
    #) 경사 초기화, 순방향 전파, 손실값 계산, 역방향 전파, 옵티마이저로 매개변수 업데이트

In [53]:
import torch.optim as optim

x = torch.Tensor([[0,0], [0,1], [1,0], [1,1]])
t= torch.Tensor([0,1,1,0])

net = Network(input_size=2, hidden_size=2, output_size=1)

loss_function = nn.BCELoss()

optimizer = optim.SGD(params=net.parameters(), lr =0.5)

STEP = 10001

for step in range(STEP):
    optimizer.zero_grad() #경사 초기화
    y=net(x)
    loss = loss_function(y.squeeze(), t)
    loss.backward() #loss에 백워드 함수 호출해서 역전파 시작
    optimizer.step()
    if step % 1000 ==0:
        print("{}:\t {:.4f}" .format(step, loss.item()))

pred = net(x).ge(0.5) #ge는 0.5 넘으면 true, 안넘으면 false로 해줌
print(pred.view(-1))

0:	 0.6927
1000:	 0.2574
2000:	 0.0210
3000:	 0.0102
4000:	 0.0067
5000:	 0.0049
6000:	 0.0039
7000:	 0.0032
8000:	 0.0028
9000:	 0.0024
10000:	 0.0021
tensor([False,  True,  True, False])


In [54]:
!pwd

/home/yunseo/notebooks


In [59]:
#pytorch dataset, dataloader

import torch
from torch.utils.data import Dataset, DataLoader
import numpy as np

class CustomDataset(Dataset):
    def __init__(self, data_path):
        with open(data_path, "r", encoding="utf-8") as file:
            data = file.read().splitlines() 
            data = np.array([line.split("\t") for line in data], dtype=float)

            self.x = data[:, :-1] #데이터는 1000개의 행, 4개의 열을 가지는 2차원 행렬
            self.t = data[:, :-1] #마지막 열이 타겟 데이터

    def __getitem__(self, index):
        return (self.x[index], self.t[index]) #인덱스에 해당하는 데이터를 가져옴

    def __len__(self):
        return len(self.x)

    def custom_collate_fn(self, data):
        x, t = list(zip(*data))
        return (torch.FloatTensor(x), torch.LongTensor(t))

example_dataset_path = "./example_dataset.tsv"
custom_dataset = CustomDataset(data_path=example_dataset_path)

train_loader = DataLoader(dataset=custom_dataset,
                          batch_size = 64,
                          collate_fn = custom_dataset.custom_collate_fn,
                          shuffle = True)

for x, y in train_loader:
    print("size of mini-batch x: {}, t: {}".format(x.size(), y.size()))
    break

        

size of mini-batch x: torch.Size([64, 3]), t: torch.Size([64, 3])


/tmp/ipykernel_1012/3562898395.py:24: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /croot/pytorch-select_1730848725855/work/torch/csrc/utils/tensor_new.cpp:274.)
  return (torch.FloatTensor(x), torch.LongTensor(t))
/tmp/ipykernel_1012/3562898395.py:24: DeprecationWarning: an integer is required (got type numpy.float64).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  return (torch.FloatTensor(x), torch.LongTensor(t))
